# Generated by Django 3.1.7 on 2021-05-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0003_auto_20210430_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('taskid', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_time', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preTasksDepartmentId', to='crm_cubedots.departments', verbose_name='Department Name')),
                ('task_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preTasksCatId', to='crm_cubedots.taskcategories', verbose_name='Task Category Name')),
            ],
            options={
                'db_table': 'pre_tasks',
            },
        ),
    ]
