# Generated by Django 3.1.7 on 2021-06-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0004_pretasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_duration',
            field=models.BigIntegerField(default=0),
        ),
    ]
