# Generated by Django 3.1.7 on 2021-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0008_auto_20210608_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretasks',
            name='required_time',
            field=models.IntegerField(default=0),
        ),
    ]
