# Generated by Django 3.1.7 on 2021-06-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0011_auto_20210608_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_duration',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
