# Generated by Django 3.2.5 on 2021-08-06 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0012_auto_20210612_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=0)),
                ('work_started_at', models.DateTimeField(blank=True, null=True)),
                ('work_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskID', to='crm_cubedots.tasks', verbose_name='Task ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasksLogUserId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_task_logs',
            },
        ),
    ]
