# Generated by Django 3.2.5 on 2021-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0014_usertaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='process_status',
            field=models.CharField(max_length=100),
        ),
    ]
