# Generated by Django 3.2.5 on 2021-08-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0015_alter_tasks_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
