# Generated by Django 3.2.5 on 2021-09-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0016_tasks_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaves_type',
            },
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(max_length=60, null=True, verbose_name='Approval Status')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(verbose_name='Reason')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='From')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='To')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_cubedots.departments', verbose_name='Department Name')),
                ('leaves_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavesTypeId', to='crm_cubedots.leavetypes', verbose_name='Leaves Type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee Name')),
            ],
            options={
                'db_table': 'leaves_applied',
            },
        ),
    ]
