# Generated by Django 3.2.5 on 2021-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0017_applyleave_leavetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
