# Generated by Django 3.2.5 on 2021-09-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0019_rename_manager_name_applyleave_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='applyleave',
            name='qc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplyLeaveQcId', to=settings.AUTH_USER_MODEL, verbose_name='QC Name'),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='tl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplyLeaveTlId', to=settings.AUTH_USER_MODEL, verbose_name='TL Name'),
        ),
    ]
