# Generated by Django 3.2.5 on 2021-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0020_auto_20210922_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='team_leader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
