# Generated by Django 3.2.5 on 2021-09-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0022_manager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table='managers',
        ),
    ]
