# Generated by Django 3.2.5 on 2021-09-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0023_alter_manager_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='tl_id',
            new_name='tl',
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerUserId', to=settings.AUTH_USER_MODEL),
        ),
    ]
