# Generated by Django 3.2.5 on 2021-09-23 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0024_auto_20210923_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='tl',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='tl_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TlId', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TlUserId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_leaders',
            },
        ),
    ]
