# Generated by Django 3.2.5 on 2021-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0026_auto_20210923_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
