# Generated by Django 3.2.5 on 2021-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0027_auto_20210923_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
