# Generated by Django 3.2.5 on 2021-09-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0029_auto_20210924_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyleave',
            old_name='qc',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='applyleave',
            name='team_leader',
        ),
    ]
