# Generated by Django 3.2.5 on 2021-09-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0030_auto_20210924_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplyLeaveQcId', to='crm_cubedots.manager', verbose_name='QC Name'),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='tl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApplyLeaveTlId', to='crm_cubedots.teamleader', verbose_name='TL Name'),
        ),
    ]
