# Generated by Django 3.2.5 on 2021-09-24 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0033_auto_20210924_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='tl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TlId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applyleave',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavesTypeManagerId', to=settings.AUTH_USER_MODEL, verbose_name='Manager Name'),
        ),
    ]
