# Generated by Django 3.2.5 on 2021-09-24 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0034_auto_20210924_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
