# Generated by Django 3.2.5 on 2021-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_cubedots', '0035_manager_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='manager_approval',
            field=models.CharField(max_length=60, null=True, verbose_name='Manager Approval Status'),
        ),
        migrations.AddField(
            model_name='applyleave',
            name='tl_approval',
            field=models.CharField(max_length=60, null=True, verbose_name='Tl Approval Status'),
        ),
    ]
